name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Mise
        uses: jdx/mise-action@v2

      - name: Link the plugin
        run: mise plugins link --force "${PWD}"
      - name: Smoke test
        run: mise --verbose x spark@latest -- spark-shell --version
